CREATE PROCEDURE [dbo].[spAddAnimal]
	@ANUMBER NVARCHAR(50),
	@COUNTRY NVARCHAR(10),
	@GENDER NVARCHAR(10),
	@MOTHERNUM NVARCHAR(50),
	@FATHERNUM NVARCHAR(50),
	@DATEBIRTH DATE,
	@HNUMBER NVARCHAR(50),
	@BIRTHPLACE NVARCHAR(50),
	@PASSPORTN NVARCHAR (50),
	@PASSPORTDATE NVARCHAR (50)
AS
BEGIN
	INSERT INTO [dbo].[Livestock] (AnimalNumber,Country,Gender,MotherNumber,FatherNumber,DateOfBirth,
	HerdNumber,PlaceOfBirth,PassportSerial,PassportDate)
	VALUES 
	(@ANUMBER,
	@COUNTRY,
	@GENDER,
	@MOTHERNUM,
	@FATHERNUM,
	@DATEBIRTH,
	@HNUMBER,
	@BIRTHPLACE,
	@PASSPORTN,
	@PASSPORTDATE)
END