CREATE PROCEDURE [dbo].[spUpdateAnimal]
	@ID INT,
	@ANUMBER NVARCHAR(50),
	@COUNTRY NVARCHAR(10),
	@GENDER NVARCHAR(10),
	@MOTHERNUM NVARCHAR(50),
	@FATHERNUM NVARCHAR(50),
	@DATEBIRTH DATE,
	@HNUMBER NVARCHAR(50),
	@BIRTHPLACE NVARCHAR(50),
	@PASSPORTN NVARCHAR (50),
	@PASSPORTDATE NVARCHAR (50)
AS
BEGIN
	SET NOCOUNT ON;
	UPDATE [dbo].[Livestock]
	SET AnimalNumber = @ANUMBER, Country = @COUNTRY,Gender = @GENDER, 
	MotherNumber = @MOTHERNUM, FatherNumber = @FATHERNUM,
	DateOfBirth = @DATEBIRTH, HerdNumber = @HNUMBER,
	PlaceOfBirth = @BIRTHPLACE, PassportSerial = @PASSPORTN,
	PassportDate = @PASSPORTDATE
	WHERE Id = @ID;
END
